export const KW = {
  study: [
    'quiet',
    'study',
    'work',
    'wifi',
    'socket',
    'outlet',
    'laptop',
    'sessiz',
    'çalışma',
    'ders',
    'priz',
    'çalışılabilir',
    'هادئ',
    'دراسة',
    'شغل',
    'واي فاي',
    'مقابس',
    'لابتوب',
  ],
  antiStudy: [
    'crowded',
    'noisy',
    'smoky',
    'kalabalık',
    'gürültülü',
    'sigara',
    'مزدحم',
    'مزعج',
    'دخان',
  ],
  romantic: [
    'romantic',
    'cozy',
    'view',
    'terrace',
    'sunset',
    'candle',
    'romantik',
    'manzara',
    'teras',
    'gün batımı',
    'loş',
    'رومانسي',
    'إطلالة',
    'غروب',
    'شموع',
  ],
  classic: [
    'classic',
    'vintage',
    'nostalgic',
    'historic',
    'traditional',
    'heritage',
    'klasik',
    'nostaljik',
    'tarihi',
    'geleneksel',
    'osmanlı',
    'meyhane',
    'konak',
    'han',
    'كلاسيكي',
    'تراثي',
    'تاريخي',
    'تقليدي',
    'عثماني',
  ],
  liveMusicHints: ['live music', 'canlı müzik', 'موسيقى حية'],
  outdoorHints: [
    'outdoor',
    'terrace',
    'patio',
    'garden',
    'açık alan',
    'teras',
    'bahçe',
    'خارجي',
    'تراس',
    'حديقة',
  ],
  coffeeHints: ['coffee', 'espresso', 'latte', 'kahve', 'قهوة'],
};
